### ISSUE TITLE
Update commands in "Deploying Istio" section

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/guide-istio-intro#106]
On Mac and extracted `istio-1.7.3.tar.gz` (the source code tar) from https://github.com/istio/istio/releases/tag/1.7.3 and get to the following command

```
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
```

Command fails as no matches are found. Extracted archive has the following in the install folder:

```
austinseto@Austins-MacBook-Pro istio-1.7.3 % ls install
consul	gcp	tools
```

I think the command provided needs to be updated. 

Also I think it should be noted that the user should extract the source code archive. I at first (on a previous test) downloaded `istio-1.7.3-osx.tar.gz` from the releases page which does not have the `install` folder inside at all.

**Comment by tt-le** [comment]
It seems that all versions of istio starting from `1.6.0` and onward do not have that path anymore. It might be because they stopped support helm custom install using helm charts. Will investigate further to find an alternative.

**Comment by gkwan-ibm** [comment]
close
- the guide was fixed
