### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-istio-intro#37]
- [x] All links in this guide do not open in a new tab

**Deploying version 1 of the hello microservice**
- [x] `mvn clean package` is `clean` needed?

**Deploying version 2 of the hello microservice**
- [x] "As defined in the `hello.yaml` file the gateway is expecting the host to be example.com." -> `hello.yaml` should be hotspotted
- [ ] "Update the traffic.yaml" arrow doesn't highlight what gets updated
- [ ] By the end of this section there are two `traffic.yaml` tabs (one from start and one from finish). Is this intended? I thought it made it confusing to the user

**Testing microservices that are running on Kubernetes**
- [x] "Create the endpoint test class in the src/test/java/it/io/openliberty/guides/rest/EndpointTest.java file:" Is this line necessary before the create command arrow?
- [x] Create the EndpointTest class arrow doesn't switch to file

**Contribute to this guide**
- [x] Is this section still needed?

**Comment by justineechen** [comment]
@proubatsis Can you address the remaining issues that are more content related?

**Comment by proubatsis** [comment]
@andrewdes 

> "Update the traffic.yaml" arrow doesn't highlight what gets updated

Confirmed with @gkwan-ibm that it doesn't need to highlight anything, the text underneath is hotspotted.

> By the end of this section there are two `traffic.yaml` tabs (one from start and one from finish). Is this intended? I thought it made it confusing to the user

This is intended, I'm not entirely sure what a more user-friendly way of displaying this is.

> Create the EndpointTest class arrow doesn't switch to file

I do not experience this problem
