### ISSUE TITLE
Introduction of blue-green could have a clearer scenarios

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guide-istio-intro#41]
When I read the intro, I felt the scenario wasn't quite clear in this section:
```
You’ll use Istio to implement blue-green deployments. The traffic shifting feature allows you to allocate a percentage of traffic to certain versions of services. You can use this feature to shift 100 percent of live traffic to blue deployments and 100 percent of test traffic to green deployments. Then, you can shift the traffic to point to the opposite deployments as necessary to perform blue-green deployments.
```
I liked the way Martin Fowler talked about it . - https://martinfowler.com/bliki/BlueGreenDeployment.html

I.e. using an upgrade scenario.  I think the main thing that's missing is talking about the testing being against a new version and once testing is complete switching the `live` traffic to it.  The 'point to opposite deployments' doesn't quite make sense to me because that implies the test traffic goes to the old deployment (pointless).  The key point is the `live` traffic is switched to the new deployment and the old deployment can be used for testing new forward development.

**Comment by gcharters** [comment]
I just found this text later on, which I really like:
```
Blue-green deployments are a way of deploying your applications such that you have two environments where your application runs. In this scenario, you will have a production environment and a test environment. At any point in time, the blue deployment can accept production traffic and the green deployment can accept test traffic, or vice-versa. When you want to deploy a new version of your application, you will deploy to the color that is currently acting as your test environment. After the new version is verified on the test environment, the traffic will be shifted over. Thus, your live traffic is now being handled by what used to be the test site.
```

**Comment by yeekangc** [comment]
@gkwan-ibm
