### ISSUE TITLE
Make Istio consistent with Kubernetes guides

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/guide-istio-intro#42]
Consider introducing a modified `name` microservice to replace `hello`. Look into other options as well, the guides should work as a sort of "series".

**Comment by gcharters** [comment]
When we created the MicroProfile guides it was a concious decision to base them on the same scenario. This has enabled them to easily be reused in workshops. I like to think of the docker, kube and Istio guides as a natural progression from the MP guides and we already plan to use all of these guides in the same workshop. I therefore think it would be very helpful if they were based on the same scenario.

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/guides-common/issues/256
