### ISSUE TITLE
Daily build test failed to build container image 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-istio-intro#64]
The daily build tests for the Istio guide has been failing to build the images from daily build: 

[ERROR] manifest for [secure]/olguides:cl190520190508-1310 not found
[ERROR] manifest for [secure]/olguides:cl190520190508-1310 not found
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project system: Could not build image: manifest for [secure]/olguides:cl190520190508-1310 not found -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

First bad build: 20190508-1310
Last good build: 20190508-0300

**Comment by evelinec** [comment]
Looks like this problem happens on some builds. ie, there are 3 builds yesterday, 2 build successfully, 1 failed.

**Comment by gkwan-ibm** [comment]
close because no happened recently
