### ISSUE TITLE
The instructions to delete resources at "Tearing down your environment" section are not clear

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-istio-intro#66]
At  "Tearing down your environment" section, under the statement "Navigate to the directory where you extracted Istio and delete the Istio resources from the cluster.", the instructions are not clear. Either
- combine the instructions for individual platform
- or add more description

**Comment by justineechen** [comment]
@gkwan-ibm I tried adding a new section within Tearing down your environment on LGDEV , what do you think?

**Comment by justineechen** [comment]
- On hold for now because there is a new design coming in for multi-platform

**Comment by gkwan-ibm** [comment]
will be addressed by https://github.com/OpenLiberty/guides-common/issues/288

**Comment by DannyS03** [comment]
Added sentence
```
This will stop any running pods created by the yaml files and delete them from the cluster.
```

![image](https://user-images.githubusercontent.com/25497083/60203562-e7f9f300-981a-11e9-8adf-2d9c5fd8c4fd.png)

Perhaps we can still go more in detail in the `Tearing down your environment` section
