### ISSUE TITLE
Remove the system.yaml in scripts direcory

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-istio-intro#69]
Remove the `system.yaml` in the `scripts` directory, and use the master copy in the `finish` directory instead. Looks like there are differences for these 2 copies of the yaml files. Perhaps one is specific for testing. If that's the case, perhaps we'd rename the `system.yaml` in the `scripts` directory to `systemTest.yaml` or simply `test.yaml`?

**Comment by gkwan-ibm** [comment]
close
- was fixed in some time
