### ISSUE TITLE
guide.net.intro

### ISSUE THREAD

**Issue by gmright2** [OpenLiberty/guide-istio-intro#90]
when net intro introduce tag master commit to guide .

**Comment by yeekangc** [comment]
@gmright2, can you elaborate on the issue that you ran into?

**Comment by gmright2** [comment]
My team and I we were try to see if it’s possible for intro- can be able to pass in log because we try to write some codes but it never pass in jira, or Travis test deploy  pipelines

**Comment by gkwan-ibm** [comment]
@gmright2 Are you asking question about the guide https://openliberty.io/guides/istio-intro.html, technical question about Istio, technical question about jira, technical question Travis, or something else?

**Comment by gmright2** [comment]
Yes sir because gmright2 try to test their guide in jira,travis but the test seem to bring arrow back

**Comment by gmright2** [comment]
Now we thinks the repostory for guide.net.intro should be created in openliberty organization or as template

**Comment by yeekangc** [comment]
@gmright2, I am not sure I follow.  What is guide.net.intro and how does it relate to the istio-intro guide here?

**Comment by gkwan-ibm** [comment]
@gmright2 This repo guide-istio-intro is used for the OpenLiberty guide https://openliberty.io/guides/istio-intro.html to explore how to manage microservice traffic using Istio. Also, it is created under the OpenLiberty organization. Are you sure it is the right place to handle your question or request about "guide.net.intro"?

**Comment by gmright2** [comment]
This issue came from gmright2 private repostory this is the first time gmright2 
Share ideas with different team we need to understand in which duration gmright2 is going for this issue was created 

https://github.com/gmright2/Gmright2.bucket.QA/issues/6#issue-587203358

**Comment by yeekangc** [comment]
We do not have the information we need to look into this issue further.  Closing.

**Comment by gmright2** [comment]
Example ![F239EE9D-9F06-467D-9DEB-20BDF12DF766](https://user-images.githubusercontent.com/59498844/78415292-6e333900-75e6-11ea-8ca5-6d0d71af4df9.png)

**Comment by gkwan-ibm** [comment]
The information does not help to understand what the issue really is and its context. Are you sure  that it is the right place to handle your question?
